package com.summarizer.enums.closedClassWords;

import java.util.Arrays;

public enum PronounsEnum {
  EU("eu"),
  TU("tu"),
  ELE("ele"),
  ELA("ela"),
  NOS_WITH_ACCENT("nós"),
  VOS_WITH_ACCENT("vós"),
  ELES("eles"),
  ELAS("elas"),
  MIM("mim"),
  COMIGO("comigo"),
  TI("ti"),
  CONTIGO("contigo"),
  CONSIGO("consigo"),
  CONVOSCO("convosco"),
  ME("me"),
  TE("te"),
  LHE("lhe"),
  LHES("lhes"),
  SE("se"),
  NOS("nos"),
  VOS("vos"),
  MEU("meu"),
  MINHA("minha"),
  MEUS("meus"),
  MINHAS("minhas"),
  TEU("teu"),
  TUA("tua"),
  TEUS("teus"),
  TUAS("tuas"),
  SEU("seu"),
  SUA("sua"),
  SEUS("seus"),
  SUAS("suas"),
  NOSSO("nosso"),
  NOSSA("nossa"),
  NOSSOS("nossos"),
  NOSSAS("nossas"),
  VOSSO("vosso"),
  VOSSA("vossa"),
  VOSSOS("vossos"),
  VOSSAS("vossas"),
  ESTE("este"),
  ESTES("estes"),
  ESTA("esta"),
  ESTAS("estas"),
  ESSE("esse"),
  ESSES("esses"),
  ESSA("essa"),
  ESSAS("essas"),
  AQUELE("aquele"),
  AQUELA("aquela"),
  AQUELES("aqueles"),
  AQUELAS("aquelas"),
  ISTO("isto"),
  ISSO("isso"),
  AQUILO("aquilo"),
  MESMO("mesmo"),
  MESMA("mesma"),
  MESMOS("mesmos"),
  MESMAS("mesmas"),
  PROPRIO_WITH_ACCENT("próprio"),
  PROPRIOS_WITH_ACCENT("próprios"),
  PROPRIA_WITH_ACCENT("própria"),
  PROPRIAS_WITH_ACCENT("próprias"),
  SEMELHANTE("semelhante"),
  TAL("tal"),
  QUE("que"),
  QUEM("quem"),
  ONDE("onde"),
  CUJO("cujo"),
  CUJA("cuja"),
  CUJOS("cujos"),
  CUJAS("cujas"),
  QUANDO("quando"),
  COMO("como"),
  QUAL("qual"),
  QUAIS("quais"),
  ALGUM("algum"),
  ALGUMA("alguma"),
  ALGUNS("alguns"),
  ALGUMAS("algumas"),
  ALGUEM_WITH_ACCENT("alguém"),
  NENHUM("nenhum"),
  NENHUMA("nenhuma"),
  NENHUNS("nenhuns"),
  NENHUMAS("nenhumas"),
  NINGUEM("ninguém"),
  TODO("todo"),
  TODA("toda"),
  TODOS("todos"),
  TODAS("todas"),
  TUDO("tudo"),
  OUTRO("outro"),
  OUTRA("outra"),
  OUTROS("outros"),
  OUTRAS("outras"),
  OUTREM("outrem"),
  MUITO("muito"),
  MUITA("muita"),
  MUITOS("muitos"),
  MUITAS("muitas"),
  POUCO("pouco"),
  POUCA("pouca"),
  POUCOS("poucos"),
  POUCAS("poucas"),
  CERTO("certo"),
  CERTOS("certos"),
  CERTA("certa"),
  CERTAS("certas"),
  VARIOS_WITH_ACCENT("vários"),
  VARIAS_WITH_ACCENT("várias"),
  TANTO("tanto"),
  TANTA("tanta"),
  TANTOS("tantos"),
  TANTAS("tantas"),
  QUANTO("quanto"),
  QUANTOS("quantos"),
  QUANTA("quanta"),
  QUANTAS("quantas"),
  QUALQUER("qualquer"),
  QUAISQUER("quaisquer"),
  NADA("nada"),
  CADA("cada"),
  ALGO("algo");

  private String description;

  PronounsEnum(String descriptrion) {
    this.description = descriptrion;
  }

  public String getDescription() {
    return this.description;
  }

  public static boolean isPronouns(String word) {
    return Arrays.stream(PronounsEnum.values())
        .map(PronounsEnum::getDescription)
        .anyMatch(pronouns -> pronouns.contains(word));
  }
}
